-- SQL script to create the PRODUCTS table
CREATE TABLE PRODUCTS (
    PRODUCT_ID              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    PRODUCT_NAME            VARCHAR2(255) NOT NULL UNIQUE,
    DESCRIPTION             VARCHAR2(1000),
    CATEGORY                VARCHAR2(100),
    UNIT_PRICE              NUMBER(10, 2),
    SUPPLIER                VARCHAR2(255),
    CURRENT_STOCK_QUANTITY  NUMBER DEFAULT 0 NOT NULL
);

COMMENT ON TABLE PRODUCTS IS 'Stores details about each unique product in inventory.';
COMMENT ON COLUMN PRODUCTS.PRODUCT_ID IS 'Unique identifier for the product.';
COMMENT ON COLUMN PRODUCTS.PRODUCT_NAME IS 'Name of the product (must be unique).';
COMMENT ON COLUMN PRODUCTS.CURRENT_STOCK_QUANTITY IS 'Current available stock quantity for the product.';