-- SQL script to create the RESTOCK_REQUESTS table
CREATE TABLE RESTOCK_REQUESTS (
    REQUEST_ID              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    PRODUCT_ID              NUMBER NOT NULL,
    QUANTITY_REQUESTED      NUMBER NOT NULL,
    REQUEST_DATE            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    STATUS                  VARCHAR2(50) DEFAULT 'Pending' NOT NULL, -- e.g., 'Pending', 'Ordered', 'Fulfilled', 'Cancelled'
    PRIORITY                VARCHAR2(50) DEFAULT 'Medium', -- e.g., 'Low', 'Medium', 'High', 'Urgent'
    REQUESTED_BY            VARCHAR2(100),
    FULFILLED_DATE          TIMESTAMP,

    -- Foreign Key constraint to link with the PRODUCTS table
    CONSTRAINT FK_PRODUCT_ID_REQ
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCTS(PRODUCT_ID)
);

COMMENT ON TABLE RESTOCK_REQUESTS IS 'Manages requests for restocking products.';
COMMENT ON COLUMN RESTOCK_REQUESTS.PRODUCT_ID IS 'Foreign key linking to the PRODUCTS table.';
COMMENT ON COLUMN RESTOCK_REQUESTS.QUANTITY_REQUESTED IS 'Quantity of product requested for restock.';
COMMENT ON COLUMN RESTOCK_REQUESTS.REQUEST_DATE IS 'Timestamp when the restock request was made.';
COMMENT ON COLUMN RESTOCK_REQUESTS.STATUS IS 'Current status of the restock request.';